#!/bin/bash
usage() { echo "Usage: $0 [-l <langcode>] [-p <project>] title..." 1>&2; exit 1; }
lang=en
project=wiktionary
for arg in "$@"; do
  shift
  case "$arg" in
    "--help") set -- "$@" "-h" ;;
    "--lang") set -- "$@" "-l" ;;
    "--project") set -- "$@" "-p" ;;
    *)        set -- "$@" "$arg"
  esac
done
while getopts ":l:p:" opt
do
    case $opt in
        l)
            lang=$OPTARG
            ;;
        p)
            project=$OPTARG
            ;;
        ?)
            usage
            ;;
    esac
done
shift $(($OPTIND - 1))
for title in "$@"; do
    title=${title// /_}
    saveto="page/${title}.wiki"
    if [[ $title == "Module:"* ]]; then saveto="${title/Module:/Module/}.lua"; fi  # Module/ works
    echo $title
    curl -o "${saveto}" --create-dirs -f -s -S -G --data-urlencode "title=${title}" --data-urlencode "action=raw" "https://${lang}.${project}.org/w/index.php"
done
