local php = {}
local dispatch = {}

php.hashValue = function(algo, value)
    if type(value) ~= 'string' then error("bad argument #2 to 'hashValue' (string expected, got number)") end
    return dispatch[algo](value)
end
-- all algorithm available in mediawiki, but not this file
php.listAlgorithms = function()
    return { "md2", "md4", "md5", "sha1", "sha224", "sha256", "sha384", "sha512/224", "sha512/256", "sha512", "sha3-224", "sha3-256", "sha3-384", "sha3-512", "ripemd128", "ripemd160", "ripemd256", "ripemd320", "whirlpool", "tiger128,3", "tiger160,3", "tiger192,3", "tiger128,4", "tiger160,4", "tiger192,4", "snefru", "snefru256", "gost", "gost-crypto", "adler32", "crc32", "crc32b", "fnv132", "fnv1a32", "fnv164", "fnv1a64", "joaat", "haval128,3", "haval160,3", "haval192,3", "haval224,3", "haval256,3", "haval128,4", "haval160,4", "haval192,4", "haval224,4", "haval256,4", "haval128,5", "haval160,5", "haval192,5", "haval224,5", "haval256,5" }
end

local pureluasha = require("php.lib.pureluasha")
dispatch["md5"]=pureluasha.md5
dispatch["sha1"]=pureluasha.sha1
dispatch["sha224"]=pureluasha.sha224
dispatch["sha256"]=pureluasha.sha256
dispatch["sha384"]=pureluasha.sha384
dispatch["sha512/224"]=pureluasha.sha512_224
dispatch["sha512/256"]=pureluasha.sha512_256
dispatch["sha512"]=pureluasha.sha512
dispatch["sha3-224"]=pureluasha.sha3_224
dispatch["sha3-256"]=pureluasha.sha3_256
dispatch["sha3-384"]=pureluasha.sha3_384
dispatch["sha3-512"]=pureluasha.sha3_512

-- generated by https://github.com/user-none/lua-{hashings,nums} with
-- sed -i 's/require("hashings/require("php.lib.hashings/g' *.lua
-- sed -i 's/require("nums/require("php.lib.nums/g' *.lua
local hashings = {}
dispatch["ripemd160"] = function(s)
    if hashings["ripemd160"] == nil then hashings["ripemd160"] = require("php.lib.hashings.ripemd160") end
    return hashings["ripemd160"](s):hexdigest():lower()
end
dispatch["whirlpool"] = function(s)
    if hashings["whirlpool"] == nil then hashings["whirlpool"] = require("php.lib.hashings.whirlpool") end
    return hashings["whirlpool"](s):hexdigest():lower()
end
dispatch["adler32"] = function(s)
    if hashings["adler32"] == nil then hashings["adler32"] = require("php.lib.hashings.adler32") end
    return hashings["adler32"](s):hexdigest():lower()
end
dispatch["crc32"] = function(s)
    if hashings["crc32"] == nil then hashings["crc32"] = require("php.lib.hashings.crc32") end
    return hashings["crc32"](s):hexdigest():lower()
end

php.opts = {}

return php
