local php = {}

local nsindex = {}
php.getNsIndex = function (s) 
    if nsindex == {} then
        for i, t in pairs(ns) do
            nsindex[t.name] = i
            for _, x in ipairs(t.aliases) do
                nsindex[x] = i
            end
        end
    end
    return nsindex[s]
end

local nszh = {
    [-2]={ ["id"]=-2, ["name"]="Media", ["canonicalName"]="Media", ["displayName"]=nil, ["hasSubpages"]=false, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=false, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={"媒体", "媒體", "媒体文件"}, ["subject"]=-2, ["talk"]=nil, ["associated"]=nil },
    [-1]={ ["id"]=-1, ["name"]="Special", ["canonicalName"]="Special", ["displayName"]=nil, ["hasSubpages"]=false, ["hasGenderDistinction"]=false, ["isCapitalized"]=true, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=false, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={"特殊"}, ["subject"]=-1, ["talk"]=nil, ["associated"]=nil },
    [0]={ ["id"]=0, ["name"]="", ["canonicalName"]="", ["displayName"]="词条", ["hasSubpages"]=false, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=true, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=0, ["talk"]=1, ["associated"]=1 },
    [1]={ ["id"]=1, ["name"]="Talk", ["canonicalName"]="Talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={"对话", "對話", "讨论", "討論"}, ["subject"]=0, ["talk"]=1, ["associated"]=0 },
    [2]={ ["id"]=2, ["name"]="User", ["canonicalName"]="User", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=true, ["isCapitalized"]=true, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={"用户", "用戶"}, ["subject"]=2, ["talk"]=3, ["associated"]=3 },
    [3]={ ["id"]=3, ["name"]="User talk", ["canonicalName"]="User talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=true, ["isCapitalized"]=true, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={"用户对话", "用戶對話", "用户讨论", "用戶討論"}, ["subject"]=2, ["talk"]=3, ["associated"]=2 },
    [4]={ ["id"]=4, ["name"]="Wiktionary", ["canonicalName"]="Project", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={"维基词典", "維基詞典"}, ["subject"]=4, ["talk"]=5, ["associated"]=5 },
    [5]={ ["id"]=5, ["name"]="Wiktionary talk", ["canonicalName"]="Project talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={"维基词典讨论", "維基詞典討論"}, ["subject"]=4, ["talk"]=5, ["associated"]=4 },
    [6]={ ["id"]=6, ["name"]="File", ["canonicalName"]="File", ["displayName"]=nil, ["hasSubpages"]=false, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={"图像", "圖像", "档案", "檔案", "文件", "Image"}, ["subject"]=6, ["talk"]=7, ["associated"]=7 },
    [7]={ ["id"]=7, ["name"]="File talk", ["canonicalName"]="File talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={"图像对话", "圖像對話", "图像讨论", "圖像討論", "档案对话", "檔案對話", "档案讨论", "檔案討論", "文件对话", "文件對話", "文件讨论", "文件討論", "Image_talk"}, ["subject"]=6, ["talk"]=7, ["associated"]=6 },
    [8]={ ["id"]=8, ["name"]="MediaWiki", ["canonicalName"]="MediaWiki", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=true, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=8, ["talk"]=9, ["associated"]=9 },
    [9]={ ["id"]=9, ["name"]="MediaWiki talk", ["canonicalName"]="MediaWiki talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=true, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={"MediaWiki讨论", "MediaWiki討論"}, ["subject"]=8, ["talk"]=9, ["associated"]=8 },
    [10]={ ["id"]=10, ["name"]="Template", ["canonicalName"]="Template", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=true, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={"模板", "样板", "樣板"}, ["subject"]=10, ["talk"]=11, ["associated"]=11 },
    [11]={ ["id"]=11, ["name"]="Template talk", ["canonicalName"]="Template talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=true, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={"模板对话", "模板對話", "模板讨论", "模板討論", "样板对话", "樣板對話", "样板讨论", "樣板討論"}, ["subject"]=10, ["talk"]=11, ["associated"]=10 },
    [12]={ ["id"]=12, ["name"]="Help", ["canonicalName"]="Help", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={"帮助", "幫助"}, ["subject"]=12, ["talk"]=13, ["associated"]=13 },
    [13]={ ["id"]=13, ["name"]="Help talk", ["canonicalName"]="Help talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={"帮助对话", "幫助對話", "帮助讨论", "幫助討論"}, ["subject"]=12, ["talk"]=13, ["associated"]=12 },
    [14]={ ["id"]=14, ["name"]="Category", ["canonicalName"]="Category", ["displayName"]=nil, ["hasSubpages"]=false, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={"分类", "分類"}, ["subject"]=14, ["talk"]=15, ["associated"]=15 },
    [15]={ ["id"]=15, ["name"]="Category talk", ["canonicalName"]="Category talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={"分类对话", "分類對話", "分类讨论", "分類討論"}, ["subject"]=14, ["talk"]=15, ["associated"]=14 },
    [100]={ ["id"]=100, ["name"]="Appendix", ["canonicalName"]="Appendix", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={"附录", "附錄"}, ["subject"]=100, ["talk"]=101, ["associated"]=101 },
    [101]={ ["id"]=101, ["name"]="Appendix talk", ["canonicalName"]="Appendix talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={"附录讨论", "附錄討論", "Appendix talk"}, ["subject"]=100, ["talk"]=101, ["associated"]=100 },
    [102]={ ["id"]=102, ["name"]="Transwiki", ["canonicalName"]="Transwiki", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=102, ["talk"]=103, ["associated"]=103 },
    [103]={ ["id"]=103, ["name"]="Transwiki talk", ["canonicalName"]="Transwiki talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={"Transwiki talk"}, ["subject"]=102, ["talk"]=103, ["associated"]=102 },
    [106]={ ["id"]=106, ["name"]="Rhymes", ["canonicalName"]="Rhymes", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={"韵部", "韻部"}, ["subject"]=106, ["talk"]=107, ["associated"]=107 },
    [107]={ ["id"]=107, ["name"]="Rhymes talk", ["canonicalName"]="Rhymes talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={"韵部讨论", "韻部討論", "Rhymes talk"}, ["subject"]=106, ["talk"]=107, ["associated"]=106 },
    [118]={ ["id"]=118, ["name"]="Reconstruction", ["canonicalName"]="Reconstruction", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={"RC"}, ["subject"]=118, ["talk"]=119, ["associated"]=119 },
    [119]={ ["id"]=119, ["name"]="Reconstruction talk", ["canonicalName"]="Reconstruction talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=118, ["talk"]=119, ["associated"]=118 },
    [828]={ ["id"]=828, ["name"]="Module", ["canonicalName"]="Module", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=true, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={"模块", "模組"}, ["subject"]=828, ["talk"]=829, ["associated"]=829 },
    [829]={ ["id"]=829, ["name"]="Module talk", ["canonicalName"]="Module talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=true, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={"模块讨论", "模組討論", "Module talk"}, ["subject"]=828, ["talk"]=829, ["associated"]=828 },
    [2300]={ ["id"]=2300, ["name"]="Gadget", ["canonicalName"]="Gadget", ["displayName"]=nil, ["hasSubpages"]=false, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=2300, ["talk"]=2301, ["associated"]=2301 },
    [2301]={ ["id"]=2301, ["name"]="Gadget talk", ["canonicalName"]="Gadget talk", ["displayName"]=nil, ["hasSubpages"]=false, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={"Gadget talk"}, ["subject"]=2300, ["talk"]=2301, ["associated"]=2300 },
    [2302]={ ["id"]=2302, ["name"]="Gadget definition", ["canonicalName"]="Gadget definition", ["displayName"]=nil, ["hasSubpages"]=false, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]="GadgetDefinition", ["aliases"]={"Gadget definition"}, ["subject"]=2302, ["talk"]=2303, ["associated"]=2303 },
    [2303]={ ["id"]=2303, ["name"]="Gadget definition talk", ["canonicalName"]="Gadget definition talk", ["displayName"]=nil, ["hasSubpages"]=false, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={"Gadget definition talk"}, ["subject"]=2302, ["talk"]=2303, ["associated"]=2302 },
}

local nsen = {
    [-2]={ ["id"]=-2, ["name"]="Media", ["canonicalName"]="Media", ["displayName"]=nil, ["hasSubpages"]=false, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=false, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=-2, ["talk"]=nil, ["associated"]=nil },
    [-1]={ ["id"]=-1, ["name"]="Special", ["canonicalName"]="Special", ["displayName"]=nil, ["hasSubpages"]=false, ["hasGenderDistinction"]=false, ["isCapitalized"]=true, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=false, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=-1, ["talk"]=nil, ["associated"]=nil },
    [0]={ ["id"]=0, ["name"]="", ["canonicalName"]="", ["displayName"]="(Main)", ["hasSubpages"]=false, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=true, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=0, ["talk"]=1, ["associated"]=1 },
    [1]={ ["id"]=1, ["name"]="Talk", ["canonicalName"]="Talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=0, ["talk"]=1, ["associated"]=0 },
    [2]={ ["id"]=2, ["name"]="User", ["canonicalName"]="User", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=true, ["isCapitalized"]=true, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=2, ["talk"]=3, ["associated"]=3 },
    [3]={ ["id"]=3, ["name"]="User talk", ["canonicalName"]="User talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=true, ["isCapitalized"]=true, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=2, ["talk"]=3, ["associated"]=2 },
    [4]={ ["id"]=4, ["name"]="Wiktionary", ["canonicalName"]="Project", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={"WT"}, ["subject"]=4, ["talk"]=5, ["associated"]=5 },
    [5]={ ["id"]=5, ["name"]="Wiktionary talk", ["canonicalName"]="Project talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=4, ["talk"]=5, ["associated"]=4 },
    [6]={ ["id"]=6, ["name"]="File", ["canonicalName"]="File", ["displayName"]=nil, ["hasSubpages"]=false, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={"Image"}, ["subject"]=6, ["talk"]=7, ["associated"]=7 },
    [7]={ ["id"]=7, ["name"]="File talk", ["canonicalName"]="File talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={"Image_talk"}, ["subject"]=6, ["talk"]=7, ["associated"]=6 },
    [8]={ ["id"]=8, ["name"]="MediaWiki", ["canonicalName"]="MediaWiki", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=true, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=8, ["talk"]=9, ["associated"]=9 },
    [9]={ ["id"]=9, ["name"]="MediaWiki talk", ["canonicalName"]="MediaWiki talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=true, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=8, ["talk"]=9, ["associated"]=8 },
    [10]={ ["id"]=10, ["name"]="Template", ["canonicalName"]="Template", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={"T"}, ["subject"]=10, ["talk"]=11, ["associated"]=11 },
    [11]={ ["id"]=11, ["name"]="Template talk", ["canonicalName"]="Template talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=10, ["talk"]=11, ["associated"]=10 },
    [12]={ ["id"]=12, ["name"]="Help", ["canonicalName"]="Help", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=12, ["talk"]=13, ["associated"]=13 },
    [13]={ ["id"]=13, ["name"]="Help talk", ["canonicalName"]="Help talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=12, ["talk"]=13, ["associated"]=12 },
    [14]={ ["id"]=14, ["name"]="Category", ["canonicalName"]="Category", ["displayName"]=nil, ["hasSubpages"]=false, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={"CAT"}, ["subject"]=14, ["talk"]=15, ["associated"]=15 },
    [15]={ ["id"]=15, ["name"]="Category talk", ["canonicalName"]="Category talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=14, ["talk"]=15, ["associated"]=14 },
    [90]={ ["id"]=90, ["name"]="Thread", ["canonicalName"]="Thread", ["displayName"]=nil, ["hasSubpages"]=false, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=90, ["talk"]=91, ["associated"]=91 },
    [91]={ ["id"]=91, ["name"]="Thread talk", ["canonicalName"]="Thread talk", ["displayName"]=nil, ["hasSubpages"]=false, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=90, ["talk"]=91, ["associated"]=90 },
    [92]={ ["id"]=92, ["name"]="Summary", ["canonicalName"]="Summary", ["displayName"]=nil, ["hasSubpages"]=false, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=92, ["talk"]=93, ["associated"]=93 },
    [93]={ ["id"]=93, ["name"]="Summary talk", ["canonicalName"]="Summary talk", ["displayName"]=nil, ["hasSubpages"]=false, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=92, ["talk"]=93, ["associated"]=92 },
    [100]={ ["id"]=100, ["name"]="Appendix", ["canonicalName"]="Appendix", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={"AP"}, ["subject"]=100, ["talk"]=101, ["associated"]=101 },
    [101]={ ["id"]=101, ["name"]="Appendix talk", ["canonicalName"]="Appendix talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=100, ["talk"]=101, ["associated"]=100 },
    [102]={ ["id"]=102, ["name"]="Concordance", ["canonicalName"]="Concordance", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=102, ["talk"]=103, ["associated"]=103 },
    [103]={ ["id"]=103, ["name"]="Concordance talk", ["canonicalName"]="Concordance talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=102, ["talk"]=103, ["associated"]=102 },
    [104]={ ["id"]=104, ["name"]="Index", ["canonicalName"]="Index", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=104, ["talk"]=105, ["associated"]=105 },
    [105]={ ["id"]=105, ["name"]="Index talk", ["canonicalName"]="Index talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=104, ["talk"]=105, ["associated"]=104 },
    [106]={ ["id"]=106, ["name"]="Rhymes", ["canonicalName"]="Rhymes", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=106, ["talk"]=107, ["associated"]=107 },
    [107]={ ["id"]=107, ["name"]="Rhymes talk", ["canonicalName"]="Rhymes talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=106, ["talk"]=107, ["associated"]=106 },
    [108]={ ["id"]=108, ["name"]="Transwiki", ["canonicalName"]="Transwiki", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=108, ["talk"]=109, ["associated"]=109 },
    [109]={ ["id"]=109, ["name"]="Transwiki talk", ["canonicalName"]="Transwiki talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=108, ["talk"]=109, ["associated"]=108 },
    [110]={ ["id"]=110, ["name"]="Thesaurus", ["canonicalName"]="Thesaurus", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={"WS", "Wikisaurus"}, ["subject"]=110, ["talk"]=111, ["associated"]=111 },
    [111]={ ["id"]=111, ["name"]="Thesaurus talk", ["canonicalName"]="Thesaurus talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={"Wikisaurus_talk"}, ["subject"]=110, ["talk"]=111, ["associated"]=110 },
    [114]={ ["id"]=114, ["name"]="Citations", ["canonicalName"]="Citations", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=114, ["talk"]=115, ["associated"]=115 },
    [115]={ ["id"]=115, ["name"]="Citations talk", ["canonicalName"]="Citations talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=114, ["talk"]=115, ["associated"]=114 },
    [116]={ ["id"]=116, ["name"]="Sign gloss", ["canonicalName"]="Sign gloss", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=116, ["talk"]=117, ["associated"]=117 },
    [117]={ ["id"]=117, ["name"]="Sign gloss talk", ["canonicalName"]="Sign gloss talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=116, ["talk"]=117, ["associated"]=116 },
    [118]={ ["id"]=118, ["name"]="Reconstruction", ["canonicalName"]="Reconstruction", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={"RC"}, ["subject"]=118, ["talk"]=119, ["associated"]=119 },
    [119]={ ["id"]=119, ["name"]="Reconstruction talk", ["canonicalName"]="Reconstruction talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=118, ["talk"]=119, ["associated"]=118 },
    [828]={ ["id"]=828, ["name"]="Module", ["canonicalName"]="Module", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={"MOD"}, ["subject"]=828, ["talk"]=829, ["associated"]=829 },
    [829]={ ["id"]=829, ["name"]="Module talk", ["canonicalName"]="Module talk", ["displayName"]=nil, ["hasSubpages"]=true, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=828, ["talk"]=829, ["associated"]=828 },
    [2300]={ ["id"]=2300, ["name"]="Gadget", ["canonicalName"]="Gadget", ["displayName"]=nil, ["hasSubpages"]=false, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=2300, ["talk"]=2301, ["associated"]=2301 },
    [2301]={ ["id"]=2301, ["name"]="Gadget talk", ["canonicalName"]="Gadget talk", ["displayName"]=nil, ["hasSubpages"]=false, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=2300, ["talk"]=2301, ["associated"]=2300 },
    [2302]={ ["id"]=2302, ["name"]="Gadget definition", ["canonicalName"]="Gadget definition", ["displayName"]=nil, ["hasSubpages"]=false, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=true, ["isTalk"]=false, ["defaultContentModel"]="GadgetDefinition", ["aliases"]={}, ["subject"]=2302, ["talk"]=2303, ["associated"]=2303 },
    [2303]={ ["id"]=2303, ["name"]="Gadget definition talk", ["canonicalName"]="Gadget definition talk", ["displayName"]=nil, ["hasSubpages"]=false, ["hasGenderDistinction"]=false, ["isCapitalized"]=false, ["isContent"]=false, ["isIncludable"]=true, ["isMovable"]=true, ["isSubject"]=false, ["isTalk"]=true, ["defaultContentModel"]=nil, ["aliases"]={}, ["subject"]=2302, ["talk"]=2303, ["associated"]=2302 },
}

for i, t in pairs(nszh) do
    for _, k in ipairs("subject", "talk", "associated") do
        if t[k] then
            t[k] = nszh[t[k]]
        end
    end
end

for i, t in pairs(nsen) do
    for _, k in ipairs("subject", "talk", "associated") do
        if t[k] then
            t[k] = nsen[t[k]]
        end
    end
end

local stats = { -- bliki
    pages=0, articles=0, files=0, edits=0, views=nil, users=0, activeUsers=0, admins=0
}

php.optszh = { -- Special:Version
    ["stats"]=stats, -- bliki
    ["currentVersion"]="1.37.0-wmf.12 (d4df395)",
    ["scriptPath"]="/w",
    ["server"]="//zh.wiktionary.org",
    ["siteName"]="Wiktionary",
    ["stylePath"]="/w/skins",
    ["namespaces"]=nszh
}

php.optsen = {
    ["stats"]=stats, -- bliki
    ["currentVersion"]="1.37.0-wmf.12 (d4df395)",
    ["scriptPath"]="/w",
    ["server"]="//en.wiktionary.org",
    ["siteName"]="Wiktionary",
    ["stylePath"]="/w/skins",
    ["namespaces"]=nsen
}

local ns = nszh
php.opts = php.optszh
php.pagesInCategory = function(category, which) return 0 end -- bliki
php.pagesInNamespace = function(ns) return 0 end -- bliki
php.usersInGroup = function(group) return 0 end -- bliki
php.interwikiMap = function(filter) -- not https://www.mediawiki.org/wiki/Extension:Scribunto/Lua_reference_manual#mw.site.interwikiMap
    local l = nil
    local cacheKey = "null"
    if filter then
        if filter == 'local' then l = 1 elseif filter == '!local' then l = 0 else return "bad argument #1 to 'interwikiMap' (unknown filter '$filter')" end
        cacheKey = filter
    end
    local interwikiMapCache = {} -- comp
    return interwikiMapCache[cacheKey] -- nil
end

return php
